---
monitor:
  enabled: true
  print_hz: .5
  ewma_tau_sec: 2.0
  warn_grace_sec: 2.0
  use_ansi_color: true

num_callback_groups: 3

bags:
  - name: "saberguide"
    bag_uri: "/home/user/00_bags"
    storage_id: "mcap"
    storage_config_file: "mcap_config.yaml"
    uri_with_datetime: true
    max_queue_bytes: 1073741824     # 1GiB MiB
    max_queue_size: 5000          # secondary cap
    bag_cache_size: 1             # GB
    overflow_policy: block  # or "block" drop_oldest
    warn_on_overflow: true
    overflow_warn_period_sec: 1.0
    compress_image: false
    jpeg_quality: 95
    png_level: 3
    compression_type: "png"
    topics:
      # mavros
      - name: "/mavros/altitude"
        type: "mavros_msgs/msg/Altitude"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 10.0
          warn_below_hz: 8.0
        callback_group_id: 0
      - name: "/mavros/estimator_status"
        type: "mavros_msgs/msg/EstimatorStatus"
        qos: "default"
        mode: "generic"
        monitor:
          expected_hz: 1.0
          warn_below_hz: .5
        callback_group_id: 0
      - name: "/mavros/imu/data_raw"
        type: "sensor_msgs/msg/Imu"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 50.0
          warn_below_hz: 30.
        callback_group_id: 0
      - name: "/mavros/imu/data"
        type: "sensor_msgs/msg/Imu"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 1.0
          warn_below_hz: .5
        callback_group_id: 0
      - name: "/mavros/imu/mag"
        type: "sensor_msgs/msg/MagneticField"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 10.
        callback_group_id: 0
      - name: "/mavros/local_position/odom"
        type: "nav_msgs/msg/Odometry"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 30.0
          warn_below_hz: 15.
        callback_group_id: 0
      - name: "/mavros/local_position/pose"
        type: "geometry_msgs/msg/PoseStamped"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 30.0
          warn_below_hz: 15.
        callback_group_id: 0
      - name: "/mavros/local_position/velocity_local"
        type: "geometry_msgs/msg/TwistStamped"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 30.0
          warn_below_hz: 8.
        callback_group_id: 0
      - name: "/mavros/px4flow/raw/optical_flow_rad"
        type: "mavros_msgs/msg/OpticalFlowRad"
        qos: "default"
        mode: "generic"
        monitor:
          expected_hz: 10.0
          warn_below_hz: 8.
        callback_group_id: 0
      
      - name: "/mavros/state"
        type: "mavros_msgs/msg/State"
        qos: "default"
        mode: "generic"
        monitor:
          expected_hz: 1.0
          warn_below_hz: .8
        callback_group_id: 0
      - name: "/mavros/vision_pose/pose"
        type: "geometry_msgs/msg/PoseStamped"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 200.0
          warn_below_hz: 100.
        callback_group_id: 0

      # microstrain
      - name: "/microstrain/imu/data"
        type: "sensor_msgs/msg/Imu"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 200.0
          warn_below_hz: 180.0
        callback_group_id: 0
      - name: "/microstrain/imu/data_raw"
        type: "sensor_msgs/msg/Imu"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 200.0
          warn_below_hz: 180.0
        callback_group_id: 0
      - name: "/microstrain/imu/mag"
        type: "sensor_msgs/msg/MagneticField"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 200.0
          warn_below_hz: 180.0
        callback_group_id: 0
      - name: "/microstrain/imu/pressure"
        type: "sensor_msgs/msg/FluidPressure"
        qos: "sensor"
        mode: "generic"
        monitor:
          expected_hz: 200.0
          warn_below_hz: 180.0
        callback_group_id: 0

      - name: "/livox/lidar"
        type: "livox_ros_driver2/msg/CustomMsg"
        qos: "default"
        mode: "typed"
        monitor:
          expected_hz: 10.0
          warn_below_hz: 9.0
        callback_group_id: 1
      - name: "/livox/points"
        type: "sensor_msgs/msg/PointCloud2"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 10.0
          warn_below_hz: 9.0
        callback_group_id: 1
      - name: "/livox/imu"
        type: "sensor_msgs/msg/Imu"
        qos: "default"
        mode: "typed"
        monitor:
          expected_hz: 200.0
          warn_below_hz: 180.0
        callback_group_id: 0

      - name: "/rslidar/points"
        type: "sensor_msgs/msg/PointCloud2"
        qos: "default"
        mode: "typed"
        monitor:
          expected_hz: 10.0
          warn_below_hz: 9.0
        callback_group_id: 1
      - name: "/rslidar/imu"
        type: "sensor_msgs/msg/Imu"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 200.0
          warn_below_hz: 180.0
        callback_group_id: 0

  - name: "saberguide_realsense"
    bag_uri: "/home/user/00_bags"
    storage_id: "mcap"
    storage_config_file: "mcap_config.yaml"
    uri_with_datetime: true
    max_queue_bytes: 1073741824     # 1GiB MiB
    max_queue_size: 5000          # secondary cap
    bag_cache_size: 2             # GB
    overflow_policy: block  # or "block" drop_oldest
    warn_on_overflow: true
    overflow_warn_period_sec: 1.0
    compress_image: false
    jpeg_quality: 95
    png_level: 3
    compression_type: "png"
    topics:
      # realsense
      - name: "/rs456/camera/color/camera_info"
        type: "sensor_msgs/msg/CameraInfo"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 12.0
        callback_group_id: 1
      - name: "/rs456/camera/color/image_raw"
        type: "sensor_msgs/msg/Image"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 12.0
        callback_group_id: 1
      - name: "/rs456/camera/depth/camera_info"
        type: "sensor_msgs/msg/CameraInfo"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 12.0
        callback_group_id: 1
      - name: "/rs456/camera/depth/image_rect_raw"
        type: "sensor_msgs/msg/Image"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 12.0
        callback_group_id: 1
      - name: "/rs456/camera/infra1/camera_info"
        type: "sensor_msgs/msg/CameraInfo"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 12.0
        callback_group_id: 1
      - name: "/rs456/camera/infra1/image_rect_raw"
        type: "sensor_msgs/msg/Image"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 12.0
        callback_group_id: 1
      - name: "/rs456/camera/infra2/camera_info"
        type: "sensor_msgs/msg/CameraInfo"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 12.0
        callback_group_id: 1
      - name: "/rs456/camera/infra2/image_rect_raw"
        type: "sensor_msgs/msg/Image"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 12.0
        callback_group_id: 1
      - name: "/rs456/camera/imu"
        type: "sensor_msgs/msg/Imu"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 200.0
          warn_below_hz: 180.0
        callback_group_id: 0

  - name: "saberguide_zed"
    bag_uri: "/home/user/00_bags"
    storage_id: "mcap"
    storage_config_file: "mcap_config.yaml"
    uri_with_datetime: true
    max_queue_bytes: 4294967296     # 1GiB MiB   2147483648=2GB, 4294967296=4GB, 8589934592=8GB
    max_queue_size: 5000          # secondary cap
    bag_cache_size: 6            # GB
    overflow_policy: block  # or "block" drop_oldest
    warn_on_overflow: true
    overflow_warn_period_sec: 1.0
    compress_image: false
    jpeg_quality: 95
    png_level: 3
    compression_type: "png"
    topics:
      # zed
      - name: "/zed/zed_node/imu/data"
        type: "sensor_msgs/msg/Imu"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 100.0
          warn_below_hz: 80.0
        callback_group_id: 0
      - name: "/zed/zed_node/imu/data_raw"
        type: "sensor_msgs/msg/Imu"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 100.0
          warn_below_hz: 80.0
        callback_group_id: 0
      #- name: "/zed/zed_node/depth/camera_info"
      #  type: "sensor_msgs/msg/CameraInfo"
      #  qos: "sensor"
     #   mode: "typed"
     #   monitor:
     #     expected_hz: 15.0
     #     warn_below_hz: 10.0
     #   callback_group_id: 1
     # - name: "/zed/zed_node/depth/depth_registered"
     #   type: "sensor_msgs/msg/Image"
     #   qos: "sensor"
     #   mode: "typed"
     #   monitor:
     #     expected_hz: 15.0
     #     warn_below_hz: 10.0
     #   callback_group_id: 1
      - name: "/zed/zed_node/left/color/raw/image/camera_info"
        type: "sensor_msgs/msg/CameraInfo"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 10.0
        callback_group_id: 1
      - name: "/zed/zed_node/left/color/raw/image"
        type: "sensor_msgs/msg/Image"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 10.0
        callback_group_id: 2
      - name: "/zed/zed_node/right/color/raw/camera_info"
        type: "sensor_msgs/msg/CameraInfo"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 10.0
        callback_group_id: 1
      - name: "/zed/zed_node/right/color/raw/image"
        type: "sensor_msgs/msg/Image"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 10.0
        callback_group_id: 2
     #- name: "/zed/zed_node/confidence/confidence_map"
     # #  type: "sensor_msgs/msg/Image"
      #  qos: "sensor"
      #  mode: "typed"
      #  monitor:
      #    expected_hz: 15.0
      #    warn_below_hz: 10.0
       # callback_group_id: 2
      - name: "/zed/zed_node/status/health"
        type: "zed_msgs/msg/HealthStatusStamped"
        qos: "sensor"
        mode: "typed"
        monitor:
          expected_hz: 15.0
          warn_below_hz: 10.0
        callback_group_id: 0

